//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.4952 版自动生成。
// 
namespace RMSPPC.ROSS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service() {
            this.Url = "http://192.168.1.166/ROSS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllowCancelFood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AllowCancelFood(string userid) {
            object[] results = this.Invoke("AllowCancelFood", new object[] {
                        userid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAllowCancelFood(string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AllowCancelFood", new object[] {
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAllowCancelFood(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AllowPresentFood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AllowPresentFood(string userid) {
            object[] results = this.Invoke("AllowPresentFood", new object[] {
                        userid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAllowPresentFood(string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AllowPresentFood", new object[] {
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndAllowPresentFood(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CurrentTableExistFood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CurrentTableExistFood(string tableno, string foodname) {
            object[] results = this.Invoke("CurrentTableExistFood", new object[] {
                        tableno,
                        foodname});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCurrentTableExistFood(string tableno, string foodname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CurrentTableExistFood", new object[] {
                        tableno,
                        foodname}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndCurrentTableExistFood(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurrentTableAllowCancelFoodQty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double GetCurrentTableAllowCancelFoodQty(string tableno, string foodname) {
            object[] results = this.Invoke("GetCurrentTableAllowCancelFoodQty", new object[] {
                        tableno,
                        foodname});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCurrentTableAllowCancelFoodQty(string tableno, string foodname, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCurrentTableAllowCancelFoodQty", new object[] {
                        tableno,
                        foodname}, callback, asyncState);
        }
        
        /// <remarks/>
        public double EndGetCurrentTableAllowCancelFoodQty(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LogOn(string userid, string password, bool WriteDog) {
            object[] results = this.Invoke("LogOn", new object[] {
                        userid,
                        password,
                        WriteDog});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogOn(string userid, string password, bool WriteDog, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogOn", new object[] {
                        userid,
                        password,
                        WriteDog}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndLogOn(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogOff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LogOff(bool WriteDog) {
            object[] results = this.Invoke("LogOff", new object[] {
                        WriteDog});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLogOff(bool WriteDog, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LogOff", new object[] {
                        WriteDog}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndLogOff(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetData(int target, int itemcount, int pageno, string tableno, string billno, string foodquery) {
            object[] results = this.Invoke("GetData", new object[] {
                        target,
                        itemcount,
                        pageno,
                        tableno,
                        billno,
                        foodquery});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetData(int target, int itemcount, int pageno, string tableno, string billno, string foodquery, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetData", new object[] {
                        target,
                        itemcount,
                        pageno,
                        tableno,
                        billno,
                        foodquery}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OpenTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int OpenTable(string tableno, int openpsncount, string userid) {
            object[] results = this.Invoke("OpenTable", new object[] {
                        tableno,
                        openpsncount,
                        userid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOpenTable(string tableno, int openpsncount, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("OpenTable", new object[] {
                        tableno,
                        openpsncount,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndOpenTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddFoodToConsumeBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddFoodToConsumeBill(string tableno, string billno, string foodcode, double addquantity, string operandis, string tastes, string userid) {
            object[] results = this.Invoke("AddFoodToConsumeBill", new object[] {
                        tableno,
                        billno,
                        foodcode,
                        addquantity,
                        operandis,
                        tastes,
                        userid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddFoodToConsumeBill(string tableno, string billno, string foodcode, double addquantity, string operandis, string tastes, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddFoodToConsumeBill", new object[] {
                        tableno,
                        billno,
                        foodcode,
                        addquantity,
                        operandis,
                        tastes,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAddFoodToConsumeBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddFoodToCancelBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddFoodToCancelBill(string tableno, string billno, string foodcode, double decquantity, string userid) {
            object[] results = this.Invoke("AddFoodToCancelBill", new object[] {
                        tableno,
                        billno,
                        foodcode,
                        decquantity,
                        userid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddFoodToCancelBill(string tableno, string billno, string foodcode, double decquantity, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddFoodToCancelBill", new object[] {
                        tableno,
                        billno,
                        foodcode,
                        decquantity,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAddFoodToCancelBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddSuitToBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AddSuitToBill(string tableno, string suitcode, string billno, double suitquantity, string userid) {
            object[] results = this.Invoke("AddSuitToBill", new object[] {
                        tableno,
                        suitcode,
                        billno,
                        suitquantity,
                        userid});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddSuitToBill(string tableno, string suitcode, string billno, double suitquantity, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddSuitToBill", new object[] {
                        tableno,
                        suitcode,
                        billno,
                        suitquantity,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndAddSuitToBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TransFood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool TransFood(string foodname, string tableno, string billno, string quantity, string operandis, string tastes, string opid, string barcode, int operatecode, string cancelrsn) {
            object[] results = this.Invoke("TransFood", new object[] {
                        foodname,
                        tableno,
                        billno,
                        quantity,
                        operandis,
                        tastes,
                        opid,
                        barcode,
                        operatecode,
                        cancelrsn});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTransFood(string foodname, string tableno, string billno, string quantity, string operandis, string tastes, string opid, string barcode, int operatecode, string cancelrsn, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TransFood", new object[] {
                        foodname,
                        tableno,
                        billno,
                        quantity,
                        operandis,
                        tastes,
                        opid,
                        barcode,
                        operatecode,
                        cancelrsn}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndTransFood(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetNewGuid() {
            object[] results = this.Invoke("GetNewGuid", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetNewGuid(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetNewGuid", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetNewGuid(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsCancelBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsCancelBill(string billno) {
            object[] results = this.Invoke("IsCancelBill", new object[] {
                        billno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsCancelBill(string billno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsCancelBill", new object[] {
                        billno}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsCancelBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsPresentBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsPresentBill(string billno) {
            object[] results = this.Invoke("IsPresentBill", new object[] {
                        billno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsPresentBill(string billno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsPresentBill", new object[] {
                        billno}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsPresentBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsCustomFood", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsCustomFood(string foodcode) {
            object[] results = this.Invoke("IsCustomFood", new object[] {
                        foodcode});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsCustomFood(string foodcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsCustomFood", new object[] {
                        foodcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsCustomFood(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddBill(string tableno, string billtypename, string userid) {
            object[] results = this.Invoke("AddBill", new object[] {
                        tableno,
                        billtypename,
                        userid});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAddBill(string tableno, string billtypename, string userid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AddBill", new object[] {
                        tableno,
                        billtypename,
                        userid}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndAddBill(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBillTypeName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBillTypeName(string billno) {
            object[] results = this.Invoke("GetBillTypeName", new object[] {
                        billno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetBillTypeName(string billno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetBillTypeName", new object[] {
                        billno}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetBillTypeName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MoveTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MoveTable(string srcTableno, string dstTableno) {
            object[] results = this.Invoke("MoveTable", new object[] {
                        srcTableno,
                        dstTableno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginMoveTable(string srcTableno, string dstTableno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("MoveTable", new object[] {
                        srcTableno,
                        dstTableno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndMoveTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTableStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetTableStatus(string Tableno) {
            object[] results = this.Invoke("GetTableStatus", new object[] {
                        Tableno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetTableStatus(string Tableno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTableStatus", new object[] {
                        Tableno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndGetTableStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CombineTable", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CombineTable(string srcTableno, string dstTableno) {
            object[] results = this.Invoke("CombineTable", new object[] {
                        srcTableno,
                        dstTableno});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCombineTable(string srcTableno, string dstTableno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CombineTable", new object[] {
                        srcTableno,
                        dstTableno}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCombineTable(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyTablePsnCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModifyTablePsnCount(string Tableno, int PsnCount) {
            object[] results = this.Invoke("ModifyTablePsnCount", new object[] {
                        Tableno,
                        PsnCount});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginModifyTablePsnCount(string Tableno, int PsnCount, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ModifyTablePsnCount", new object[] {
                        Tableno,
                        PsnCount}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndModifyTablePsnCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
}
